name: Trigger Release and Publish Page Workflow

permissions:
  contents: read
  issues: read
  pages: read
  id-token: write

# Trigger on Main branch
on:
  push:
    branches:
      - main

jobs:
  release-job:
    # Only runs if commit message starts with "release"
    if: startsWith(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run release tasks
        run: |
          echo "Deploy triggered by commit ${{ github.event.head_commit.message }}"

      - name: Trigger GitHub Pages Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/github_pages.yaml/dispatches
